#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

# Nhật ký của lần chạy này. Chạy lại được: giá trị đã ghi sẽ thành mặc định.
# Tệp này KHÔNG vào kho; nó mang dấu thời gian thao tác, chỗ của nó là OSF.
ENV_FILE="${ENV_FILE:-zenodo_21282517_nhatky.env}"

RECORD_URL="https://zenodo.org/records/21282517"
CORRECT_RELATED_URL="https://github.com/thuyhuongctu/M-AIDA/tree/v7.1.1"
ACCESS_CONDITIONS="Source files are under controlled access while the joint copyright registration with Can Tho University completes. The software itself is licensed AGPL-3.0-only and the full source is public at https://github.com/thuyhuongctu/M-AIDA"

banner "Zenodo 21282517: sửa siêu dữ liệu M-AIDA"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Mở bản ghi và vào chế độ sửa"
say "Sửa siêu dữ liệu KHÔNG sinh DOI mới. Tệp đã nộp thì bất biến, còn"
say "siêu dữ liệu thì sửa được, kể cả sau khi đã publish."
open_url "$RECORD_URL"
step "Đăng nhập nếu Zenodo hỏi."
step "Bấm nút Edit trên trang bản ghi."
pause "Đã vào được biểu mẫu sửa chưa?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Kiểm liên kết Related works TRƯỚC khi đổi gì"
warn "Bước này quyết định có được xoá tag v7.1.1 hay không. Đừng bỏ qua."
say "Bản ghi đang trỏ Is supplement to tới:"
note "  thuyhuongctu-cell/M-AIDA/tree/v7.1.1"
say "'thuyhuongctu-cell' là tên tài khoản KHÁC với 'thuyhuongctu'."
step "Tìm mục Related works, mở liên kết đó ở tab mới, đợi tải xong."
say ""
ask ZENODO_RELATED_STATUS "Liên kết ra cái gì (404 / khac / dung):"
write_env ZENODO_RELATED_STATUS "$ZENODO_RELATED_STATUS"

if [[ "$ZENODO_RELATED_STATUS" == "404" ]]; then
  ZENODO_RELATED_HOST="khong-tai-duoc"
  note "Liên kết chết sẵn. Xoá tag không làm gì tệ hơn, nhưng URL vẫn phải sửa."
else
  say ""
  warn "Trang tải được KHÔNG có nghĩa là URL đúng."
  say "GitHub tự chuyển hướng tên tài khoản cũ sang tên mới sau khi đổi tên."
  step "Nhìn thanh địa chỉ SAU KHI trang tải xong, không phải lúc vừa bấm."
  ask ZENODO_RELATED_HOST "Thanh địa chỉ hiện gì (cell / chinh):"
  if [[ "$ZENODO_RELATED_HOST" == "chinh" ]]; then
    warn "Đó là chuyển hướng, không phải liên kết đúng."
    note "URL lưu trong bản ghi vẫn là tên cũ. Nếu sau này có người đăng ký lại"
    note "tên đó thì liên kết trỏ sang kho của họ. Bắt buộc phải sửa."
  else
    warn "Tài khoản 'thuyhuongctu-cell' tồn tại thật và là người khác."
    note "Bản ghi đang dẫn nguồn gốc về kho không thuộc quyền chị. Bắt buộc sửa."
  fi
fi
write_env ZENODO_RELATED_HOST "$ZENODO_RELATED_HOST"

say ""
step "Sửa URL trong ô Related works thành:"
note "  $CORRECT_RELATED_URL"
if confirm "Đã sửa URL chưa?"; then
  ZENODO_RELATED_URL_FIXED="co"
else
  ZENODO_RELATED_URL_FIXED="chua"
  SKIPPED+=("Sửa URL Related works thành $CORRECT_RELATED_URL")
fi
write_env ZENODO_RELATED_URL_FIXED "$ZENODO_RELATED_URL_FIXED"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Điền điều kiện truy cập"
note "Chặng này đứng TRƯỚC chặng giấy phép có chủ ý: nếu dừng giữa chừng,"
note "bản ghi không rơi vào trạng thái khai giấy phép mở mà tệp vẫn khoá"
note "và không có một dòng nào giải thích vì sao."
say ""
say "Nguyên văn cần dán, lấy từ .zenodo.json trong kho:"
printf '\n%s%s%s\n\n' "$DIM" "$ACCESS_CONDITIONS" "$RESET"
step "Tìm ô điều kiện truy cập; nó hiện ra khi chế độ tệp là Restricted."
note "Zenodo có thể gọi ô này là Conditions hoặc tên gần giống. Làm theo nghĩa."
step "Dán nguyên văn đoạn trên."
pause "Đã dán xong chưa?"
write_env ZENODO_ACCESS_CONDITIONS_SET "co"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Đổi giấy phép sang AGPL-3.0-only"
say "Bản ghi đang để 'Other (Not Open)'. Đó là dấu vết của tệp .zenodo.json cũ,"
say "không phải một quyết định về giấy phép."
step "Tìm mục Licence, xoá giấy phép đang có, chọn đúng mục này:"
note "  GNU Affero General Public License v3.0 only    (mã: AGPL-3.0-only)"
warn "Đừng chọn nhầm bản 'or later'. Kho khai 'only'."
pause "Đã chọn AGPL-3.0-only chưa?"
write_env ZENODO_LICENSE "AGPL-3.0-only"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Giữ nguyên chế độ Restricted"
warn "Chặng này là KIỂM, không phải đổi. Đừng chuyển sang Open."
say "Tệp phải ở Restricted chừng nào hồ sơ đồng sở hữu với Trường chưa xong."
step "Xác nhận mục Files vẫn đang là Restricted."
if confirm "Files đang ở Restricted đúng không?"; then
  :
else
  warn "Chuyển lại về Restricted trước khi đi tiếp."
  pause "Đã chuyển lại chưa?"
fi
write_env ZENODO_ACCESS_RIGHT "restricted"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Publish"
say "Publish ở đây chỉ lưu siêu dữ liệu. DOI 10.5281/zenodo.21282517 giữ nguyên."
step "Chụp màn hình biểu mẫu TRƯỚC khi bấm, để đưa vào nhật ký sai lệch OSF."
pause "Đã chụp chưa?"
if confirm "Bấm Publish bây giờ?"; then
  step "Bấm Publish."
  pause "Zenodo đã báo lưu xong chưa?"
  ZENODO_PUBLISHED="co"
else
  warn "Bỏ qua Publish. Mọi thứ vừa sửa vẫn là bản nháp."
  ZENODO_PUBLISHED="chua"
  SKIPPED+=("Publish bản ghi Zenodo 21282517")
fi
write_env ZENODO_PUBLISHED "$ZENODO_PUBLISHED"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Xác minh sau khi publish, và kết luận về tag"
open_url "$RECORD_URL"
step "Trang bản ghi phải hiện giấy phép AGPL-3.0-only."
step "Phần điều kiện truy cập hiện đoạn vừa dán."
step "Mở lại liên kết Related works, lần này phải ra thẳng thuyhuongctu/M-AIDA."
step "Chụp màn hình SAU khi sửa."
ask ZENODO_VERIFIED "Bốn thứ trên đã đúng cả chưa (co / chua):"
write_env ZENODO_VERIFIED "$ZENODO_VERIFIED"

say ""
warn "Còn một điều kiện nữa, và nó mới là điều kiện thật cho việc xoá tag."
say "Xoá tag chỉ an toàn nếu bản lưu trữ Zenodo là một ảnh chụp ĐỘC LẬP,"
say "chứ không phải con trỏ tới tag. Cách kiểm: bản ghi có liệt kê tệp không."
step "Nhìn mục Files của bản ghi."
note "Có tên tệp hiện ra, dù kèm ổ khoá và không tải được: đó là ảnh chụp thật."
note "Không thấy tệp nào: bản ghi rỗng, và xoá tag là mất luôn nguồn gốc."
ask ZENODO_FILES_LISTED "Mục Files có liệt kê tệp không (co / khong):"
write_env ZENODO_FILES_LISTED "$ZENODO_FILES_LISTED"

say ""
if [[ "$ZENODO_PUBLISHED" == "co" && "$ZENODO_VERIFIED" == "co" && "$ZENODO_FILES_LISTED" == "co" ]]; then
  printf '  %s✓ Đủ ba điều kiện. Được phép xoá release và tag v7.1.1 trong%s\n' "$GREEN" "$RESET"
  printf '  %s  thuyhuongctu/M-AIDA.%s\n' "$GREEN" "$RESET"
  TAG_V711_AN_TOAN_DE_XOA="co"
  note "Tag đó đang trỏ vào 8a17340, tức mới hơn v7.1.2 một tháng."
  note "Nếu sau này cần lại, tạo tag cùng tên là liên kết giải được như cũ;"
  note "Zenodo lưu chuỗi URL chứ không chụp lại nội dung ở đầu kia."
else
  printf '  %s⚠ CHƯA đủ điều kiện. Đừng xoá tag v7.1.1.%s\n' "$YELLOW" "$RESET"
  TAG_V711_AN_TOAN_DE_XOA="chua"
  [[ "$ZENODO_PUBLISHED"    == "co" ]] || note "  thiếu: chưa publish"
  [[ "$ZENODO_VERIFIED"     == "co" ]] || note "  thiếu: chưa xác minh xong"
  [[ "$ZENODO_FILES_LISTED" == "co" ]] || note "  thiếu: bản ghi không liệt kê tệp nào"
  SKIPPED+=("Xoá release và tag v7.1.1, sau khi đủ ba điều kiện ở chặng 7")
fi
write_env TAG_V711_AN_TOAN_DE_XOA "$TAG_V711_AN_TOAN_DE_XOA"

finish
note "Dán $ENV_FILE cùng hai ảnh chụp vào nhật ký sai lệch OSF, đừng đưa vào kho."
